<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ include file="header.jsp" %>

			<h1>Contact</h1>
			<div class="row">
                <div class="span12">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla turpis est, tempus eget hendrerit vitae, mattis id urna. Nulla nec sodales sapien. Nullam nec tristique nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur ut ante vel purus pretium facilisis. Maecenas consectetur, augue a porta convallis, erat mauris malesuada leo, nec hendrerit ante tellus ut velit. Praesent nibh nisi, convallis elementum dignissim sed, luctus nec mi. Etiam faucibus, orci sit amet aliquam tempor, tellus nunc gravida elit, ac dictum eros nulla quis dolor. Integer ullamcorper porta nibh a semper. Curabitur justo lacus, ornare eu euismod sit amet, suscipit a turpis. Vivamus in metus magna, et cursus nulla. Nunc malesuada eros tempor justo elementum hendrerit. </p>
                    <p>Nam non ullamcorper dui. Quisque quis ullamcorper dolor. Integer mattis rhoncus arcu non imperdiet. Donec eu lectus orci. Duis accumsan pretium leo, quis volutpat nulla pharetra sit amet. Aliquam erat volutpat. Fusce consectetur magna in arcu bibendum convallis. Donec metus magna, rhoncus sed imperdiet vel, placerat vitae metus. Nunc rhoncus, mauris sed euismod lacinia, quam est sodales diam, sed aliquet sapien nibh nec libero. Fusce pretium, justo sit amet accumsan tempus, enim nunc posuere erat, vehicula iaculis purus lectus nec sem. Etiam convallis iaculis nibh, in vestibulum odio auctor et. Aliquam posuere nibh eget ligula ullamcorper laoreet. In in viverra lacus.</p>
                    <p>Morbi laoreet bibendum commodo. Aliquam hendrerit venenatis ligula, a consectetur orci egestas sit amet. Maecenas non ante nisl. Vestibulum vel facilisis quam. Vivamus nec felis nibh, sit amet adipiscing nunc. Nullam blandit, risus non fermentum pharetra, lectus mi porttitor felis, vel porta neque orci in elit. Aliquam non quam in nulla lacinia auctor nec eget lorem. Duis hendrerit pellentesque commodo. Ut scelerisque tempus elit, vitae suscipit turpis rutrum vitae. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque convallis massa quis diam egestas bibendum. Integer pellentesque mollis neque, id sodales tortor pulvinar ut. Vivamus nec consequat ipsum. Nam vel consectetur leo. Etiam vulputate dolor eget dui ullamcorper auctor.</p>
                </div>
            </div>

<%@ include file="footer.jsp" %>